#pragma once
#include "Core/Core.h"

#define STATIC_MESH_ROOT_DESCRIPTOR_TABLE_PIXEL_SRV_INDEX_DIFFUSE 0
#define STATIC_MESH_ROOT_DESCRIPTOR_TABLE_PIXEL_SRV_INDEX_SPECULAR 1
#define STATIC_MESH_ROOT_DESCRIPTOR_TABLE_PIXEL_SRV_INDEX_NORMAL 2
#define STATIC_MESH_ROOT_CONSTANT_INDEX_MATERIAL 3
#define STATIC_MESH_ROOT_CONSTANT_INDEX_TRANSFORM 4

#define DYNAMIC_MESH_ROOT_DESCRIPTOR_TABLE_PIXEL_DIFFUSE_INDEX 0
#define DYNAMIC_MESH_ROOT_DESCRIPTOR_TABLE_PIXEL_SPECULAR_INDEX 1
#define DYNAMIC_MESH_ROOT_DESCRIPTOR_TABLE_PIXEL_NORMAL_INDEX 2
#define DYNAMIC_MESH_ROOT_CONSTANT_INDEX_MATERIAL 3
#define DYNAMIC_MESH_ROOT_CONSTANT_INDEX_TRANSFORM 4
#define DYNAMIC_MESH_ROOT_CONSTANT_INDEX_BONE 5


//namespace Ideal
//{
//	enum EPipelineStateInputLayout
//	{
//		EPS_SimpleInputElement,
//		EPS_InputLayout
//	};
//
//	enum EPipelineStateVS
//	{
//		EPS_SimpleVS,
//		EPS_PipelineStateVSCount
//	};
//
//	enum EPipelineStatePS
//	{
//		EPS_SimplePS,
//		EPS_PipelineStatePSCount
//	};
//}